export enum InfraTag {
  DB_CONNECTIVITY = 'DB_CONNECTIVITY',
  REDIS_CONNECTIVITY = 'REDIS_CONNECTIVITY',
  BOOTSTRAP = 'BOOTSTRAP',
}

export enum ServiceTag {
  EVENTS_SERVICE = 'EVENTS_SERVICE',
  PROVIDER_SERVICE = 'PROVIDER_SERVICE',
}

export enum ProcessingTag {
  EVENT_ACCEPTED = 'EVENT_ACCEPTED',
  EVENT_DUPLICATE = 'EVENT_DUPLICATE',
  PROCESSING_STARTED = 'PROCESSING_STARTED',
  PROCESSING_SUCCEEDED = 'PROCESSING_SUCCEEDED',
  PROCESSING_FAILED = 'PROCESSING_FAILED',
  PROCESSING_DEFERRED = 'PROCESSING_DEFERRED',
  RETRY_SCHEDULED = 'RETRY_SCHEDULED',
  IDEMPOTENT_REPLAY = 'IDEMPOTENT_REPLAY',
  RECOVERY = 'RECOVERY',
  JOB_STALLED = 'JOB_STALLED',
}
